"use client";

import React from "react";
import { Button } from "../ui/button";
import Link from "next/link";
import { Download } from "lucide-react";

const DownloadBtn = ({
  title,
  summary,
  fileName,
  createdAt,
}: {
  title: string;
  summary: string;
  fileName: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Cenerated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}
    
${summary}
    
Original File: ${fileName}
Generated by Sommaire
`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z09]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button className="bg-rose-200 hover:bg-rose-300" onClick={handleDownload}>
      <Download className="h-8 w-8 text-rose-600" />
      <p className="text-sm text-rose-600 font-medium">
        Download Summary
      </p>
    </Button>
  );
};

export default DownloadBtn;
